### ISSUE TITLE
Junk were found in the sense vectors.

### ISSUE THREAD

**Issue by Abhishek-IIT007** [uhh-lt/sensegram#20]
When i trained sensegram on my corpus. There were no words like "afliates" present. Not even in the wordvectors file produced ("affiliate" was present though). But when i searched in the vocab of sense vectors i got words like "afliated", "affli" etc. Why does this happen? Does it follow fast-text's method of training?

**Comment by alexanderpanchenko** [comment]
Hello,

Can you please provide more details about your training settings? Which
commands did you execute exactly? Can you provide a link to the input data
to reproduce?
